### ISSUE TITLE
PUT /friends

### ISSUE THREAD

**Issue by arnopensource** [abc3354/CODEV-back#37]
give an answer to a friend request

the profile id must be of someone who is making a friends request to the current user

**Comment by Newintel** [comment]
Embedded in #44 
Route : PUT /friends/{id}
Body : boolean (true to accept, false to refuse)
Return: boolean (true if accepted, false if refused)

**Comment by Newintel** [comment]
Replace PUT /friends/{id} by PUT /friends with body 
```json 
{
    "id" : string;
    "accepted" : boolean;
}
```
